### PR TITLE
Explicit RNG support

### PR DESCRIPTION
**Pull request by cstjean**
I added explicit RNG support for Adaboost too, only to realize that it's not using the RNG... Right? If that's the case, then I can remove it before merging.

### CODE REVIEW

**Comment by cstjean** [comment]
Arrrr, apparently `Base.GLOBAL_RNG` didn't exist in Julia 0.3. Not sure what can be done about it except disabling the feature over there. Or... are you ready to stop supporting 0.3? We could REQUIRE 0.4 from now on. 0.3 users wouldn't benefit from the new features, but that seems fair at this point.

**Comment by bensadeghi** [comment]
Hi Cédric,

Thanks so much for this PR.
It all looks great, but I don't think the RNG functionality justifies breaking support for v0.3 yet. Let's hold off until v0.5 has been formally released, and we'll pull this merge in.

What do you think?

**Comment by cstjean** [comment]
That's reasonable, although I'll note that bumping up the REQUIRE to Julia 0.4 won't break DecisionTree.jl for Julia 0.3 users - it will just leave them on the current 0.4.2 branch forever. So waiting for 0.5 to land won't make any practical difference for 0.3 users unless we're planning to add new features in the meantime. The other option is to add 0.3 support to this PR, and I wouldn't mind doing it if it's important to you.

But I'm fine with waiting, I'm almost at the end of my PR spree anyway 😄

**Comment by cstjean** [comment]
Can I merge and bump the REQUIRE to Julia 0.4?

**Comment by cstjean** [comment]
Thank you! I'll try to fix the deprecation warnings this week.

**Comment by bensadeghi** [comment]
Merged.
I just bumped the require, readme and travis files to reflect the drop of support for Julia 0.3 and addition of support for Julia 0.5

Thanks for all your work on this!!

**Pull request merged**
