### PR TITLE
use AbstractVector and AbstractMatrix

### PR DESCRIPTION
**Pull request by bensadeghi**

### CODE REVIEW

**Comment by barucden** [comment]
Hi @bensadeghi, thanks for the quick response. This change is maybe more aggressive than I originally had in my mind. I am kinda new to Julia, but I believe that changing the type of the structure fields from `Vector{T}` to `AbstractVector{T}` is unnecessary. Actually, it is even discouraged in [the Julia manual](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-fields-with-abstract-type-1). I think that the following changes would be sufficient.
```
diff --git a/src/classification/main.jl b/src/classification/main.jl
index a362518..cea51f1 100644
--- a/src/classification/main.jl
+++ b/src/classification/main.jl
@@ -138,9 +138,9 @@ function prune_tree(tree::LeafOrNode{S, T}, purity_thresh=1.0) where {S, T}
 end
 
 
-apply_tree(leaf::Leaf{T}, feature::Vector{S}) where {S, T} = leaf.majority
+apply_tree(leaf::Leaf{T}, feature::AbstractVector{S}) where {S, T} = leaf.majority
 
-function apply_tree(tree::Node{S, T}, features::Vector{S}) where {S, T}
+function apply_tree(tree::Node{S, T}, features::AbstractVector{S}) where {S, T}
     if tree.featid == 0
         return apply_tree(tree.left, features)
     elseif features[tree.featid] < tree.featval
@@ -150,7 +150,7 @@ function apply_tree(tree::Node{S, T}, features::Vector{S}) where {S, T}
     end
 end
 
-function apply_tree(tree::LeafOrNode{S, T}, features::Matrix{S}) where {S, T}
+function apply_tree(tree::LeafOrNode{S, T}, features::AbstractMatrix{S}) where {S, T}
     N = size(features,1)
     predictions = Array{T}(undef, N)
     for i in 1:N
```

**Comment by bensadeghi** [comment]
The AbstractVector is the struct fields are still typed, so I think they'll be ok. I'll run a few benchmarks later when I get the chance, but for now, I'm pushing the changes to v0.10.6

**Comment by barucden** [comment]
There is [another recommendation](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-fields-with-abstract-containers-1) in the manual, which points out an ambiguity that arises from this approach. I can run the benchmark if you want me to; I just need to include the `runbenchmarks.jl` file, right?

**Comment by bensadeghi** [comment]
Hmmm, interesting...

Yeah, just run that file and compare v0.10.5 against v0.10.6

Thanks

**Comment by barucden** [comment]
I ran the benchmarks yesterday, and the results are not that different. I am attaching the benchmark outputs so you can check yourself.

[benchmark-master.txt](https://github.com/bensadeghi/DecisionTree.jl/files/4917579/benchmark-master.txt)
[benchmark-v0.10.5.txt](https://github.com/bensadeghi/DecisionTree.jl/files/4917580/benchmark-v0.10.5.txt)

**Comment by bensadeghi** [comment]
Thanks so much for running the benchmarks!!
I ran some benchmarks too, comparing v0.10.6 and the [diffs](https://github.com/bensadeghi/DecisionTree.jl/pull/129/files) in #129 ... and noticed that non-abstract types in structs resulted in slightly quicker runs. I also checked the memory footprint of RF models (in RAM and on disk), with no differences there. So I've reverted back the structs to use non-abstracts, pushed to v0.10.7.
Thanks again for your help with this

**Pull request merged**
